---
# tasks file for dotfiles

- name: Copy file
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: 0755
  with_items:
    - foo.sh
    - bar.sh

- name: Copy foo.sh to test.sh
  copy:
    src: "foo.sh"
    dest: "{{ ansible_env.HOME }}/test.sh"
    mode: 0755

- name: ls
  command: ls -i {{ ansible_env.HOME }}/
  register: inode1

- name: Run
  shell: "{{ ansible_env.HOME }}/test.sh > {{ ansible_env.HOME }}/log.txt"
  register: result_check
  async: 60
  poll: 0

- name: Override bar (cp)
  shell: "cp {{ ansible_env.HOME }}/bar.sh {{ ansible_env.HOME }}/test.sh"
  when: not bar_override_copy_module

- name: Override bar (copy module)
  copy:
    src: "bar.sh"
    dest: "{{ ansible_env.HOME }}/test.sh"
    mode: 0755
  when: bar_override_copy_module

- name: ls
  command: ls -i {{ ansible_env.HOME }}/
  register: inode2

- name: wait
  async_status:
    jid: "{{ result_check.ansible_job_id }}"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  delay: 1

- name: Result file
  shell: "cat {{ ansible_env.HOME }}/log.txt"
  register: result_file

- name: Show inode (before)
  debug:
    var: inode1.stdout

- name: Show inode (after)
  debug:
    var: inode2.stdout

- name: Show result
  debug:
    msg: "{{ result_file.stdout }}"
