name: GitHub Actions
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  playbook:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: init
        run: make init
      - name: playbook
        run: make playbook
