name: GitHub Actions
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  playbook:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          # - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: playbook
        run: ansible-playbook -i hosts site.yml
